spring:
  main:
    banner-mode: "off"
    log-startup-info: "off"
logging:
  pattern:
    console: "{\"level\": \"%p\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"
  logback:
    rollingpolicy:
      max-history: 0
      clean-history-on-start: false
